// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RollerCoastersColumns holds the columns for the "roller_coasters" table.
	RollerCoastersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "roller-coaster"},
		{Name: "location", Type: field.TypeString, Default: "Lisbon, Portugal"},
		{Name: "height", Type: field.TypeFloat64, Default: 0},
		{Name: "speed", Type: field.TypeFloat64, Default: 0},
	}
	// RollerCoastersTable holds the schema information for the "roller_coasters" table.
	RollerCoastersTable = &schema.Table{
		Name:       "roller_coasters",
		Columns:    RollerCoastersColumns,
		PrimaryKey: []*schema.Column{RollerCoastersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RollerCoastersTable,
	}
)

func init() {
}
