// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"http-go/ent/predicate"
	"http-go/ent/rollercoaster"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeRollerCoaster = "RollerCoaster"
)

// RollerCoasterMutation represents an operation that mutates the RollerCoaster nodes in the graph.
type RollerCoasterMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	location      *string
	height        *float64
	addheight     *float64
	speed         *float64
	addspeed      *float64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*RollerCoaster, error)
	predicates    []predicate.RollerCoaster
}

var _ ent.Mutation = (*RollerCoasterMutation)(nil)

// rollercoasterOption allows management of the mutation configuration using functional options.
type rollercoasterOption func(*RollerCoasterMutation)

// newRollerCoasterMutation creates new mutation for the RollerCoaster entity.
func newRollerCoasterMutation(c config, op Op, opts ...rollercoasterOption) *RollerCoasterMutation {
	m := &RollerCoasterMutation{
		config:        c,
		op:            op,
		typ:           TypeRollerCoaster,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRollerCoasterID sets the ID field of the mutation.
func withRollerCoasterID(id int) rollercoasterOption {
	return func(m *RollerCoasterMutation) {
		var (
			err   error
			once  sync.Once
			value *RollerCoaster
		)
		m.oldValue = func(ctx context.Context) (*RollerCoaster, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RollerCoaster.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRollerCoaster sets the old RollerCoaster of the mutation.
func withRollerCoaster(node *RollerCoaster) rollercoasterOption {
	return func(m *RollerCoasterMutation) {
		m.oldValue = func(context.Context) (*RollerCoaster, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RollerCoasterMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RollerCoasterMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RollerCoasterMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RollerCoasterMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RollerCoaster.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *RollerCoasterMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *RollerCoasterMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the RollerCoaster entity.
// If the RollerCoaster object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RollerCoasterMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *RollerCoasterMutation) ResetName() {
	m.name = nil
}

// SetLocation sets the "location" field.
func (m *RollerCoasterMutation) SetLocation(s string) {
	m.location = &s
}

// Location returns the value of the "location" field in the mutation.
func (m *RollerCoasterMutation) Location() (r string, exists bool) {
	v := m.location
	if v == nil {
		return
	}
	return *v, true
}

// OldLocation returns the old "location" field's value of the RollerCoaster entity.
// If the RollerCoaster object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RollerCoasterMutation) OldLocation(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLocation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLocation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLocation: %w", err)
	}
	return oldValue.Location, nil
}

// ResetLocation resets all changes to the "location" field.
func (m *RollerCoasterMutation) ResetLocation() {
	m.location = nil
}

// SetHeight sets the "height" field.
func (m *RollerCoasterMutation) SetHeight(f float64) {
	m.height = &f
	m.addheight = nil
}

// Height returns the value of the "height" field in the mutation.
func (m *RollerCoasterMutation) Height() (r float64, exists bool) {
	v := m.height
	if v == nil {
		return
	}
	return *v, true
}

// OldHeight returns the old "height" field's value of the RollerCoaster entity.
// If the RollerCoaster object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RollerCoasterMutation) OldHeight(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHeight is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHeight requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHeight: %w", err)
	}
	return oldValue.Height, nil
}

// AddHeight adds f to the "height" field.
func (m *RollerCoasterMutation) AddHeight(f float64) {
	if m.addheight != nil {
		*m.addheight += f
	} else {
		m.addheight = &f
	}
}

// AddedHeight returns the value that was added to the "height" field in this mutation.
func (m *RollerCoasterMutation) AddedHeight() (r float64, exists bool) {
	v := m.addheight
	if v == nil {
		return
	}
	return *v, true
}

// ResetHeight resets all changes to the "height" field.
func (m *RollerCoasterMutation) ResetHeight() {
	m.height = nil
	m.addheight = nil
}

// SetSpeed sets the "speed" field.
func (m *RollerCoasterMutation) SetSpeed(f float64) {
	m.speed = &f
	m.addspeed = nil
}

// Speed returns the value of the "speed" field in the mutation.
func (m *RollerCoasterMutation) Speed() (r float64, exists bool) {
	v := m.speed
	if v == nil {
		return
	}
	return *v, true
}

// OldSpeed returns the old "speed" field's value of the RollerCoaster entity.
// If the RollerCoaster object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RollerCoasterMutation) OldSpeed(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSpeed is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSpeed requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSpeed: %w", err)
	}
	return oldValue.Speed, nil
}

// AddSpeed adds f to the "speed" field.
func (m *RollerCoasterMutation) AddSpeed(f float64) {
	if m.addspeed != nil {
		*m.addspeed += f
	} else {
		m.addspeed = &f
	}
}

// AddedSpeed returns the value that was added to the "speed" field in this mutation.
func (m *RollerCoasterMutation) AddedSpeed() (r float64, exists bool) {
	v := m.addspeed
	if v == nil {
		return
	}
	return *v, true
}

// ResetSpeed resets all changes to the "speed" field.
func (m *RollerCoasterMutation) ResetSpeed() {
	m.speed = nil
	m.addspeed = nil
}

// Where appends a list predicates to the RollerCoasterMutation builder.
func (m *RollerCoasterMutation) Where(ps ...predicate.RollerCoaster) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RollerCoasterMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RollerCoasterMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RollerCoaster, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RollerCoasterMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RollerCoasterMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RollerCoaster).
func (m *RollerCoasterMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RollerCoasterMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.name != nil {
		fields = append(fields, rollercoaster.FieldName)
	}
	if m.location != nil {
		fields = append(fields, rollercoaster.FieldLocation)
	}
	if m.height != nil {
		fields = append(fields, rollercoaster.FieldHeight)
	}
	if m.speed != nil {
		fields = append(fields, rollercoaster.FieldSpeed)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RollerCoasterMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case rollercoaster.FieldName:
		return m.Name()
	case rollercoaster.FieldLocation:
		return m.Location()
	case rollercoaster.FieldHeight:
		return m.Height()
	case rollercoaster.FieldSpeed:
		return m.Speed()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RollerCoasterMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case rollercoaster.FieldName:
		return m.OldName(ctx)
	case rollercoaster.FieldLocation:
		return m.OldLocation(ctx)
	case rollercoaster.FieldHeight:
		return m.OldHeight(ctx)
	case rollercoaster.FieldSpeed:
		return m.OldSpeed(ctx)
	}
	return nil, fmt.Errorf("unknown RollerCoaster field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RollerCoasterMutation) SetField(name string, value ent.Value) error {
	switch name {
	case rollercoaster.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case rollercoaster.FieldLocation:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLocation(v)
		return nil
	case rollercoaster.FieldHeight:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHeight(v)
		return nil
	case rollercoaster.FieldSpeed:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSpeed(v)
		return nil
	}
	return fmt.Errorf("unknown RollerCoaster field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RollerCoasterMutation) AddedFields() []string {
	var fields []string
	if m.addheight != nil {
		fields = append(fields, rollercoaster.FieldHeight)
	}
	if m.addspeed != nil {
		fields = append(fields, rollercoaster.FieldSpeed)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RollerCoasterMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case rollercoaster.FieldHeight:
		return m.AddedHeight()
	case rollercoaster.FieldSpeed:
		return m.AddedSpeed()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RollerCoasterMutation) AddField(name string, value ent.Value) error {
	switch name {
	case rollercoaster.FieldHeight:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddHeight(v)
		return nil
	case rollercoaster.FieldSpeed:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSpeed(v)
		return nil
	}
	return fmt.Errorf("unknown RollerCoaster numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RollerCoasterMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RollerCoasterMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RollerCoasterMutation) ClearField(name string) error {
	return fmt.Errorf("unknown RollerCoaster nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RollerCoasterMutation) ResetField(name string) error {
	switch name {
	case rollercoaster.FieldName:
		m.ResetName()
		return nil
	case rollercoaster.FieldLocation:
		m.ResetLocation()
		return nil
	case rollercoaster.FieldHeight:
		m.ResetHeight()
		return nil
	case rollercoaster.FieldSpeed:
		m.ResetSpeed()
		return nil
	}
	return fmt.Errorf("unknown RollerCoaster field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RollerCoasterMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RollerCoasterMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RollerCoasterMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RollerCoasterMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RollerCoasterMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RollerCoasterMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RollerCoasterMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown RollerCoaster unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RollerCoasterMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown RollerCoaster edge %s", name)
}
