// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"http-go/ent/predicate"
	"http-go/ent/rollercoaster"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RollerCoasterDelete is the builder for deleting a RollerCoaster entity.
type RollerCoasterDelete struct {
	config
	hooks    []Hook
	mutation *RollerCoasterMutation
}

// Where appends a list predicates to the RollerCoasterDelete builder.
func (rcd *RollerCoasterDelete) Where(ps ...predicate.RollerCoaster) *RollerCoasterDelete {
	rcd.mutation.Where(ps...)
	return rcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rcd *RollerCoasterDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rcd.sqlExec, rcd.mutation, rcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rcd *RollerCoasterDelete) ExecX(ctx context.Context) int {
	n, err := rcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rcd *RollerCoasterDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rollercoaster.Table, sqlgraph.NewFieldSpec(rollercoaster.FieldID, field.TypeInt))
	if ps := rcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rcd.mutation.done = true
	return affected, err
}

// RollerCoasterDeleteOne is the builder for deleting a single RollerCoaster entity.
type RollerCoasterDeleteOne struct {
	rcd *RollerCoasterDelete
}

// Where appends a list predicates to the RollerCoasterDelete builder.
func (rcdo *RollerCoasterDeleteOne) Where(ps ...predicate.RollerCoaster) *RollerCoasterDeleteOne {
	rcdo.rcd.mutation.Where(ps...)
	return rcdo
}

// Exec executes the deletion query.
func (rcdo *RollerCoasterDeleteOne) Exec(ctx context.Context) error {
	n, err := rcdo.rcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rollercoaster.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rcdo *RollerCoasterDeleteOne) ExecX(ctx context.Context) {
	if err := rcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
