// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"http-go/ent/predicate"
	"http-go/ent/rollercoaster"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RollerCoasterQuery is the builder for querying RollerCoaster entities.
type RollerCoasterQuery struct {
	config
	ctx        *QueryContext
	order      []rollercoaster.OrderOption
	inters     []Interceptor
	predicates []predicate.RollerCoaster
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RollerCoasterQuery builder.
func (rcq *RollerCoasterQuery) Where(ps ...predicate.RollerCoaster) *RollerCoasterQuery {
	rcq.predicates = append(rcq.predicates, ps...)
	return rcq
}

// Limit the number of records to be returned by this query.
func (rcq *RollerCoasterQuery) Limit(limit int) *RollerCoasterQuery {
	rcq.ctx.Limit = &limit
	return rcq
}

// Offset to start from.
func (rcq *RollerCoasterQuery) Offset(offset int) *RollerCoasterQuery {
	rcq.ctx.Offset = &offset
	return rcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rcq *RollerCoasterQuery) Unique(unique bool) *RollerCoasterQuery {
	rcq.ctx.Unique = &unique
	return rcq
}

// Order specifies how the records should be ordered.
func (rcq *RollerCoasterQuery) Order(o ...rollercoaster.OrderOption) *RollerCoasterQuery {
	rcq.order = append(rcq.order, o...)
	return rcq
}

// First returns the first RollerCoaster entity from the query.
// Returns a *NotFoundError when no RollerCoaster was found.
func (rcq *RollerCoasterQuery) First(ctx context.Context) (*RollerCoaster, error) {
	nodes, err := rcq.Limit(1).All(setContextOp(ctx, rcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rollercoaster.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rcq *RollerCoasterQuery) FirstX(ctx context.Context) *RollerCoaster {
	node, err := rcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RollerCoaster ID from the query.
// Returns a *NotFoundError when no RollerCoaster ID was found.
func (rcq *RollerCoasterQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rcq.Limit(1).IDs(setContextOp(ctx, rcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rollercoaster.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rcq *RollerCoasterQuery) FirstIDX(ctx context.Context) int {
	id, err := rcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RollerCoaster entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RollerCoaster entity is found.
// Returns a *NotFoundError when no RollerCoaster entities are found.
func (rcq *RollerCoasterQuery) Only(ctx context.Context) (*RollerCoaster, error) {
	nodes, err := rcq.Limit(2).All(setContextOp(ctx, rcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rollercoaster.Label}
	default:
		return nil, &NotSingularError{rollercoaster.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rcq *RollerCoasterQuery) OnlyX(ctx context.Context) *RollerCoaster {
	node, err := rcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RollerCoaster ID in the query.
// Returns a *NotSingularError when more than one RollerCoaster ID is found.
// Returns a *NotFoundError when no entities are found.
func (rcq *RollerCoasterQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rcq.Limit(2).IDs(setContextOp(ctx, rcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rollercoaster.Label}
	default:
		err = &NotSingularError{rollercoaster.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rcq *RollerCoasterQuery) OnlyIDX(ctx context.Context) int {
	id, err := rcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RollerCoasters.
func (rcq *RollerCoasterQuery) All(ctx context.Context) ([]*RollerCoaster, error) {
	ctx = setContextOp(ctx, rcq.ctx, ent.OpQueryAll)
	if err := rcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RollerCoaster, *RollerCoasterQuery]()
	return withInterceptors[[]*RollerCoaster](ctx, rcq, qr, rcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rcq *RollerCoasterQuery) AllX(ctx context.Context) []*RollerCoaster {
	nodes, err := rcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RollerCoaster IDs.
func (rcq *RollerCoasterQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rcq.ctx.Unique == nil && rcq.path != nil {
		rcq.Unique(true)
	}
	ctx = setContextOp(ctx, rcq.ctx, ent.OpQueryIDs)
	if err = rcq.Select(rollercoaster.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rcq *RollerCoasterQuery) IDsX(ctx context.Context) []int {
	ids, err := rcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rcq *RollerCoasterQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rcq.ctx, ent.OpQueryCount)
	if err := rcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rcq, querierCount[*RollerCoasterQuery](), rcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rcq *RollerCoasterQuery) CountX(ctx context.Context) int {
	count, err := rcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rcq *RollerCoasterQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rcq.ctx, ent.OpQueryExist)
	switch _, err := rcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rcq *RollerCoasterQuery) ExistX(ctx context.Context) bool {
	exist, err := rcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RollerCoasterQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rcq *RollerCoasterQuery) Clone() *RollerCoasterQuery {
	if rcq == nil {
		return nil
	}
	return &RollerCoasterQuery{
		config:     rcq.config,
		ctx:        rcq.ctx.Clone(),
		order:      append([]rollercoaster.OrderOption{}, rcq.order...),
		inters:     append([]Interceptor{}, rcq.inters...),
		predicates: append([]predicate.RollerCoaster{}, rcq.predicates...),
		// clone intermediate query.
		sql:  rcq.sql.Clone(),
		path: rcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RollerCoaster.Query().
//		GroupBy(rollercoaster.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rcq *RollerCoasterQuery) GroupBy(field string, fields ...string) *RollerCoasterGroupBy {
	rcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RollerCoasterGroupBy{build: rcq}
	grbuild.flds = &rcq.ctx.Fields
	grbuild.label = rollercoaster.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.RollerCoaster.Query().
//		Select(rollercoaster.FieldName).
//		Scan(ctx, &v)
func (rcq *RollerCoasterQuery) Select(fields ...string) *RollerCoasterSelect {
	rcq.ctx.Fields = append(rcq.ctx.Fields, fields...)
	sbuild := &RollerCoasterSelect{RollerCoasterQuery: rcq}
	sbuild.label = rollercoaster.Label
	sbuild.flds, sbuild.scan = &rcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RollerCoasterSelect configured with the given aggregations.
func (rcq *RollerCoasterQuery) Aggregate(fns ...AggregateFunc) *RollerCoasterSelect {
	return rcq.Select().Aggregate(fns...)
}

func (rcq *RollerCoasterQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rcq); err != nil {
				return err
			}
		}
	}
	for _, f := range rcq.ctx.Fields {
		if !rollercoaster.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rcq.path != nil {
		prev, err := rcq.path(ctx)
		if err != nil {
			return err
		}
		rcq.sql = prev
	}
	return nil
}

func (rcq *RollerCoasterQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RollerCoaster, error) {
	var (
		nodes = []*RollerCoaster{}
		_spec = rcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RollerCoaster).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RollerCoaster{config: rcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rcq *RollerCoasterQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rcq.querySpec()
	_spec.Node.Columns = rcq.ctx.Fields
	if len(rcq.ctx.Fields) > 0 {
		_spec.Unique = rcq.ctx.Unique != nil && *rcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rcq.driver, _spec)
}

func (rcq *RollerCoasterQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rollercoaster.Table, rollercoaster.Columns, sqlgraph.NewFieldSpec(rollercoaster.FieldID, field.TypeInt))
	_spec.From = rcq.sql
	if unique := rcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rcq.path != nil {
		_spec.Unique = true
	}
	if fields := rcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rollercoaster.FieldID)
		for i := range fields {
			if fields[i] != rollercoaster.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rcq *RollerCoasterQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rcq.driver.Dialect())
	t1 := builder.Table(rollercoaster.Table)
	columns := rcq.ctx.Fields
	if len(columns) == 0 {
		columns = rollercoaster.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rcq.sql != nil {
		selector = rcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rcq.ctx.Unique != nil && *rcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rcq.predicates {
		p(selector)
	}
	for _, p := range rcq.order {
		p(selector)
	}
	if offset := rcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RollerCoasterGroupBy is the group-by builder for RollerCoaster entities.
type RollerCoasterGroupBy struct {
	selector
	build *RollerCoasterQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rcgb *RollerCoasterGroupBy) Aggregate(fns ...AggregateFunc) *RollerCoasterGroupBy {
	rcgb.fns = append(rcgb.fns, fns...)
	return rcgb
}

// Scan applies the selector query and scans the result into the given value.
func (rcgb *RollerCoasterGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rcgb.build.ctx, ent.OpQueryGroupBy)
	if err := rcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RollerCoasterQuery, *RollerCoasterGroupBy](ctx, rcgb.build, rcgb, rcgb.build.inters, v)
}

func (rcgb *RollerCoasterGroupBy) sqlScan(ctx context.Context, root *RollerCoasterQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rcgb.fns))
	for _, fn := range rcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rcgb.flds)+len(rcgb.fns))
		for _, f := range *rcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RollerCoasterSelect is the builder for selecting fields of RollerCoaster entities.
type RollerCoasterSelect struct {
	*RollerCoasterQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rcs *RollerCoasterSelect) Aggregate(fns ...AggregateFunc) *RollerCoasterSelect {
	rcs.fns = append(rcs.fns, fns...)
	return rcs
}

// Scan applies the selector query and scans the result into the given value.
func (rcs *RollerCoasterSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rcs.ctx, ent.OpQuerySelect)
	if err := rcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RollerCoasterQuery, *RollerCoasterSelect](ctx, rcs.RollerCoasterQuery, rcs, rcs.inters, v)
}

func (rcs *RollerCoasterSelect) sqlScan(ctx context.Context, root *RollerCoasterQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rcs.fns))
	for _, fn := range rcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
