// Code generated by ent, DO NOT EDIT.

package ent

import (
	"http-go/ent/rollercoaster"
	"http-go/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	rollercoasterFields := schema.RollerCoaster{}.Fields()
	_ = rollercoasterFields
	// rollercoasterDescName is the schema descriptor for name field.
	rollercoasterDescName := rollercoasterFields[0].Descriptor()
	// rollercoaster.DefaultName holds the default value on creation for the name field.
	rollercoaster.DefaultName = rollercoasterDescName.Default.(string)
	// rollercoasterDescLocation is the schema descriptor for location field.
	rollercoasterDescLocation := rollercoasterFields[1].Descriptor()
	// rollercoaster.DefaultLocation holds the default value on creation for the location field.
	rollercoaster.DefaultLocation = rollercoasterDescLocation.Default.(string)
	// rollercoasterDescHeight is the schema descriptor for height field.
	rollercoasterDescHeight := rollercoasterFields[2].Descriptor()
	// rollercoaster.DefaultHeight holds the default value on creation for the height field.
	rollercoaster.DefaultHeight = rollercoasterDescHeight.Default.(float64)
	// rollercoasterDescSpeed is the schema descriptor for speed field.
	rollercoasterDescSpeed := rollercoasterFields[3].Descriptor()
	// rollercoaster.DefaultSpeed holds the default value on creation for the speed field.
	rollercoaster.DefaultSpeed = rollercoasterDescSpeed.Default.(float64)
}
