// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// RollerCoaster is the predicate function for rollercoaster builders.
type RollerCoaster func(*sql.Selector)
